// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkTIr4NuVuYuwX0Mu2X6TXrcH3h3w9QkU',
    appId: '1:1051625771373:web:e7f8416b28914cab008a64',
    messagingSenderId: '1051625771373',
    projectId: 'mhealthapp-9377f',
    authDomain: 'mhealthapp-9377f.firebaseapp.com',
    storageBucket: 'mhealthapp-9377f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZKslft-VOtcL08_6nvnb25_vw1C3f2_4',
    appId: '1:1051625771373:android:e1d2643406f100bd008a64',
    messagingSenderId: '1051625771373',
    projectId: 'mhealthapp-9377f',
    storageBucket: 'mhealthapp-9377f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBncQusg8q16yGowe54SJovGl-C_ImStiA',
    appId: '1:1051625771373:ios:efab5e1da648b822008a64',
    messagingSenderId: '1051625771373',
    projectId: 'mhealthapp-9377f',
    storageBucket: 'mhealthapp-9377f.appspot.com',
    iosBundleId: 'com.example.projectCdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBncQusg8q16yGowe54SJovGl-C_ImStiA',
    appId: '1:1051625771373:ios:0d54e24af1a3a749008a64',
    messagingSenderId: '1051625771373',
    projectId: 'mhealthapp-9377f',
    storageBucket: 'mhealthapp-9377f.appspot.com',
    iosBundleId: 'com.example.projectCdm.RunnerTests',
  );
}
